SghlaDotCom/Models/DAL/AccessControl/AccessControlModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SghlaDotCom.Models.DAL.AccessControl
{
    public class AccessControlModel
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("اسم الفعالية")]
        public string functionalityName { get; set; }

        [Required]
        [DisplayName("اسم المتحكم")]
        public string controllerName { get; set; }

        [Required]
        [DisplayName("اسم الدالة")]
        public string actionMethodName { get; set; }

        [DisplayName("الادوار المسموحة")]
        public string allowRoles { get; set; }

        [DisplayName("الادوار الممنوعة")]
        public string preventedRoles { get; set; }

        [DisplayName("المستخدمين المسموح لهم بالدخول")]
        public string allowedUsers { get; set; }
    }
}

SghlaDotCom/Controllers/AccessControlModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SghlaDotCom.Models.DAL;
using SghlaDotCom.Models.DAL.AccessControl;
using System.Reflection;
using static SghlaDotCom.Startup;
using System.Diagnostics;
using SghlaDotCom.Models;
using SghlaDotCom.Helper;
using SghlaDotCom.Models.ViewModels.TreeStruct;

namespace SghlaDotCom.Controllers
{
    [Title(Title = "ربط الصلاحيات بمكونات النظام")]
    public class AccessControlModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AccessControlModels
        [Title(Title = "جدول ربط الصلاحيات بمكونات النظام")]
        [ModifiedAuthorize]
        public ActionResult Index()
        {
            return View(db.AccessControlTable.ToList());
        }

        // GET: AccessControlModels/Details/5
        [Title(Title = "تفاصيل ربط الصلاحيات بمكونات النظام")]
        [ModifiedAuthorize]
        public ActionResult Details(int? id)
        {
            List<string> list = new List<string>();
            Assembly assembly = Assembly.GetAssembly(typeof(MvcApplication));
            IEnumerable<Type> types = assembly.GetTypes().Where(type => typeof(Controller).IsAssignableFrom(type)).OrderBy(x => x.Name);
            foreach (Type cls in types.Where(a => a.Name == "HomeController"))
            {
                if (cls.IsDefined(typeof(TitleAttribute)))
                {
                    var tttt = cls.GetCustomAttribute<TitleAttribute>();
                    Debug.WriteLine(tttt.Title);
                    int a = 0;
                }
                IEnumerable<MemberInfo> memberInfo = cls.GetMethods(BindingFlags.Instance | BindingFlags.DeclaredOnly | BindingFlags.Public).Where(m => !m.GetCustomAttributes(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), true).Any()).OrderBy(x => x.Name);
                foreach (MemberInfo method in memberInfo)
                {
                    if (method.ReflectedType.IsPublic && !method.IsDefined(typeof(NonActionAttribute)) && method.IsDefined(typeof(TitleAttribute)))
                    {
                        var tttt = method.GetCustomAttribute<TitleAttribute>();
                        Debug.WriteLine(tttt.Title);
                        int a = 0;
                    }
                }
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccessControlModel accessControlModel = db.AccessControlTable.Find(id);
            if (accessControlModel == null)
            {
                return HttpNotFound();
            }
            return View(accessControlModel);
        }

        // GET: AccessControlModels/Create
        [Title(Title = "انشاء ربط صلاحية بمكونات النظام")]
        [ModifiedAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: AccessControlModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModifiedAuthorize]
        public ActionResult Create([Bind(Include = "ID,functionalityName,controllerName,actionMethodName,allowRoles,preventedRoles,allowedUsers")] AccessControlModel accessControlModel)
        {
            if (ModelState.IsValid)
            {
                db.AccessControlTable.Add(accessControlModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accessControlModel);
        }

        // GET: AccessControlModels/Edit/5
        [Title(Title = "تعديل ربط صلاحية بمكونات النظام")]
        [ModifiedAuthorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccessControlModel accessControlModel = db.AccessControlTable.Find(id);
            if (accessControlModel == null)
            {
                return HttpNotFound();
            }
            return View(accessControlModel);
        }

        // POST: AccessControlModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModifiedAuthorize]
        public ActionResult Edit([Bind(Include = "ID,functionalityName,controllerName,actionMethodName,allowRoles,preventedRoles,allowedUsers")] AccessControlModel accessControlModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(accessControlModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accessControlModel);
        }

        // GET: AccessControlModels/Delete/5
        [Title(Title = "مسح ربط صلاحية بمكونات النظام")]
        [ModifiedAuthorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccessControlModel accessControlModel = db.AccessControlTable.Find(id);
            if (accessControlModel == null)
            {
                return HttpNotFound();
            }
            return View(accessControlModel);
        }

        // POST: AccessControlModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Title(Title = "تاكيد مسح ربط صلاحية بمكونات النظام")]
        [ModifiedAuthorize]
        public ActionResult DeleteConfirmed(int id)
        {
            AccessControlModel accessControlModel = db.AccessControlTable.Find(id);
            db.AccessControlTable.Remove(accessControlModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Title(Title = "التحكم الكامل بربط صلاحية بمكونات النظام")]

        public ActionResult GetTree(string sentRole, string sentUser)
        {
            string user = "";
            string role = String.IsNullOrEmpty(sentRole) ? db.Roles.First().Name : db.Roles.First(a => a.Name == sentRole).Name;

            if (db.Users.Any(a => a.UserName == sentUser))
                user = String.IsNullOrEmpty(sentUser) ? db.Users.First().UserName : db.Users.First(a => a.UserName == sentUser).UserName;
            else
                user = db.Users.First().UserName;
            // get controllers naes
            List<string> controllerNames = new List<string>();
            HelperClasses.GetSubClasses<Controller>().ForEach(type => controllerNames.Add(type.Name));

            var tree = new TreeNode("MainClass", "هيكلية الموقع");
            foreach (var _controller in controllerNames)
            {

                // get all sub assemblies with specified type, then filter only ones inherited from controller 
                Assembly assembly = Assembly.GetAssembly(typeof(MvcApplication));
                IEnumerable<Type> types = assembly.GetTypes().Where(type => typeof(Controller).IsAssignableFrom(type)).OrderBy(x => x.Name);

                // first controller matching name and Title attribute get his name
                var attribute = types.FirstOrDefault(a => a.Name == _controller).GetCustomAttributes(typeof(Startup.TitleAttribute), true)
                     .Cast<Startup.TitleAttribute>()
                     .FirstOrDefault();

                if (attribute != null)
                {
                    var cont = new TreeNode(attribute.Title, _controller);
                    // loop through all type with maching contoller name
                    foreach (Type cls in types.Where(a => a.Name == _controller))
                    {

                        IEnumerable<MemberInfo> memberInfo = cls.GetMethods(BindingFlags.Instance | BindingFlags.DeclaredOnly | BindingFlags.Public).
                            Where(m => !m.GetCustomAttributes(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), true).Any()).OrderBy(x => x.Name);

                        // get all controller AM
                        foreach (MemberInfo method in memberInfo)
                        {
                            if (method.ReflectedType.IsPublic && method.IsDefined(typeof(Startup.TitleAttribute)))
                            {
                                bool chk = db.AccessControlTable.Any(a => a.allowRoles.Contains(role) && a.actionMethodName == method.Name && a.controllerName == _controller);
                                bool chkAllowedUsers = db.AccessControlTable.Any(a => a.allowedUsers.Contains(user) && a.actionMethodName == method.Name && a.controllerName == _controller);

                                var acMethodAtt = method.GetCustomAttributes(typeof(Startup.TitleAttribute), true)
                                                    .Cast<Startup.TitleAttribute>()
                                                    .FirstOrDefault();

                                if (acMethodAtt != null)
                                {
                                    var action = new TreeNode(acMethodAtt.Title, _controller + "_____" + method.Name, chk, chkAllowedUsers);
                                    //     var actionUser = new TreeNode(acMethodAtt.Title, _controller + "_____" + method.Name, chk, chkAllowedUsers);
                                    if (!cont.ContainsChild(attribute.Title))
                                    {
                                        cont.Add(action);
                                    }
                                }

SghlaDotCom/Views/AccessControlModels/Create.cshtml
@model SghlaDotCom.Models.DAL.AccessControl.AccessControlModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccessControlModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.functionalityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.functionalityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.functionalityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.controllerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.controllerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.controllerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.actionMethodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.actionMethodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.actionMethodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.allowRoles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.allowRoles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.allowRoles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preventedRoles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preventedRoles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preventedRoles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.allowedUsers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.allowedUsers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.allowedUsers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SghlaDotCom/Views/AccessControlModels/Delete.cshtml
@model SghlaDotCom.Models.DAL.AccessControl.AccessControlModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AccessControlModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.functionalityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.functionalityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.controllerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.controllerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actionMethodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actionMethodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.allowRoles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.allowRoles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preventedRoles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preventedRoles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.allowedUsers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.allowedUsers)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SghlaDotCom/Views/AccessControlModels/Details.cshtml
@model SghlaDotCom.Models.DAL.AccessControl.AccessControlModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AccessControlModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.functionalityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.functionalityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.controllerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.controllerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actionMethodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actionMethodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.allowRoles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.allowRoles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preventedRoles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preventedRoles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.allowedUsers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.allowedUsers)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SghlaDotCom/Views/AccessControlModels/Edit.cshtml
@model SghlaDotCom.Models.DAL.AccessControl.AccessControlModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccessControlModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.functionalityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.functionalityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.functionalityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.controllerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.controllerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.controllerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.actionMethodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.actionMethodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.actionMethodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.allowRoles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.allowRoles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.allowRoles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preventedRoles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preventedRoles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preventedRoles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.allowedUsers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.allowedUsers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.allowedUsers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SghlaDotCom/Views/AccessControlModels/GetTree.cshtml
@model SghlaDotCom.Models.ViewModels.TreeStruct.TreeNode
@{
    ViewBag.Title = "GetTree";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="/assets/global/plugins/jstree/dist/themes/default/style.min.css" />
<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <div id="tree_1" class="tree-demo">
                    <ul>
                        <li>
                            هيكلية الموقع
                            <ul>
                                @foreach (var node_1 in Model.GetNodes())
                                {
                                    <li data-jstree='{ "opened" : true }' id="@node_1.id">
                                        <a href="javascript:;">
                                            @node_1.text
                                        </a>
                                        <ul>
                                            @foreach (var node_2 in node_1.GetNodes())
                                            {
                                                <li data-jstree='{ "type" : "icon"}' id="@node_2.id">
                                                    @node_2.text
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                @using (Html.BeginForm("GetTree", "AccessControlModels", FormMethod.Post, new { id = "myForm" }))
                {
                    <div class="row">
                        <div class="col-md-8">
                            @Html.DropDownList("roles", null, htmlAttributes: new { @class = "form-control", onChange = "check(this);" })
                        </div>
                        <div class="col-md-4">
                            <input type="submit" value="ارسال" class="btn btn-default" />
                        </div>
                    </div>

                    <input type="hidden" id="authorized" name="authorized" required />

                }
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <div id="tree_2" class="tree-demo">
                    <ul>
                        <li>
                            هيكلية الموقع
                            <ul>
                                @foreach (var node_1 in Model.GetNodes())
                                {
                                    <li data-jstree='{ "opened" : true }' id="@node_1.id">
                                        <a href="javascript:;">
                                            @node_1.text
                                        </a>
                                        <ul>
                                            @foreach (var node_2 in node_1.GetNodes())
                                            {
                                                <li data-jstree='{ "type" : "icon"}' id="@node_2.id">
                                                    @node_2.text
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                @using (Html.BeginForm("GetTree", "AccessControlModels", FormMethod.Post, new { id = "myForm2" }))
                {
                    <div class="row">
                        <div class="col-md-8">

                            @Html.DropDownList("sentUsers", null, htmlAttributes: new { @class = "form-control", onChange = "checkUser(this);" })


                        </div>
                        <div class="col-md-4">
                            <input type="submit" value="ارسال" class="btn btn-default" />
                        </div>
                    </div>
                        <input type="hidden" id="dealWithUsers2" name="dealWithUsers2" value="1" />
                        <input type="hidden" id="authorized2" name="authorized2" required />
                }
            </div>
        </div>
    </div>
</div>
<br />
@section pageLevelScripts{
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assets/global/plugins/jstree/dist/jstree.min.js"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script src="/assets/admin/pages/scripts/ui-tree.js"></script>
    <script>
        var tree = $("#tree_1").jstree({
            "core": {
                "check_callback": false,
                "multiple": true
            },
            "checkbox": {
                "three_state": true, // to avoid that fact that checking a node also check others
                "whole_node": false,  // to avoid checking the box just clicking the node
                //   "tie_selection": false // for checking without selecting and selecting without checking
            },
            "types": {
                "default": {
                }
            },
            "plugins": ["themes", "checkbox", "sort", "ui", "real_checkboxes"],
        })
        $("#myForm").submit(function (event) {
            var ttt = "";
            for (var i = 0; i < $('#tree_1').jstree('get_selected').length; i++) {
                if (i == ($('#tree_1').jstree('get_selected').length - 1)) {
                    ttt += $('#tree_1').jstree('get_selected')[i];
                } else {
                    ttt += $('#tree_1').jstree('get_selected')[i] + ',';
                }
            }
            console.log('ttt = ' + ttt)
            $('#authorized').val(ttt);
        });



        @foreach (var node_1 in Model.GetNodes())
        {
            foreach (var node_2 in node_1.GetNodes().Where(a => a.selectedForRoles == true)) {

                    <text>
        tree.jstree('select_node', '@node_2.id');
        </text>

            }
        }

        function check(elem) {
            window.location.href = "/@ViewContext.RouteData.Values["controller"].ToString()/@ViewContext.RouteData.Values["action"].ToString()?sentRole=" + document.getElementById("roles").options[document.getElementById("roles").selectedIndex].value + "&sentUser=" + +document.getElementById("sentUsers").options[document.getElementById("sentUsers").selectedIndex].value
        }
    </script>

    <script>

        var tree2 = $("#tree_2").jstree({
            "core": {
                "check_callback": false,
                "multiple": true
            },
            "checkbox": {
                "three_state": true, // to avoid that fact that checking a node also check others
                "whole_node": false,  // to avoid checking the box just clicking the node
                //   "tie_selection": false // for checking without selecting and selecting without checking
            },
            "types": {
                "default": {
                }
            },
            "plugins": ["themes", "checkbox", "sort", "ui", "real_checkboxes"],
        })

        $("#myForm2").submit(function (event) {
            var ttt = "";
            for (var i = 0; i < $('#tree_2').jstree('get_selected').length; i++) {
                if (i == ($('#tree_2').jstree('get_selected').length - 1)) {
                    ttt += $('#tree_2').jstree('get_selected')[i];
                } else {
                    ttt += $('#tree_2').jstree('get_selected')[i] + ',';
                }
            }
            console.log('ttt = ' + ttt)
            $('#authorized2').val(ttt);
        });



        @foreach (var node_1 in Model.GetNodes())
        {
            foreach (var node_2 in node_1.GetNodes().Where(a=>a.selectedForUsers == true)) {


                    <text>
        tree2.jstree('select_node', '@node_2.id');
        console.log('treeeeeeee2');
        </text>

            }
        }

        function checkUser(elem) {
            window.location.href = "/@ViewContext.RouteData.Values["controller"].ToString()/@ViewContext.RouteData.Values["action"].ToString()?sentRole=" + document.getElementById("roles").options[document.getElementById("roles").selectedIndex].value + "&sentUser=" + document.getElementById("sentUsers").options[document.getElementById("sentUsers").selectedIndex].value
        }
    </script>
}

@section callComponent{
    UITree.init();
}

SghlaDotCom/Views/AccessControlModels/Index.cshtml
@model IEnumerable<SghlaDotCom.Models.DAL.AccessControl.AccessControlModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.functionalityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.controllerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.actionMethodName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.allowRoles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.preventedRoles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.allowedUsers)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.functionalityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.controllerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.actionMethodName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.allowRoles)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.preventedRoles)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.allowedUsers)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>